// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace GMap.NET
{
	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	[XmlRoot("gpx", Namespace = "http://www.topografix.com/GPX/1/1", IsNullable = false)]
	public class gpxType
	{

		private metadataType metadataField;

		private wptType[] wptField;

		private rteType[] rteField;

		private trkType[] trkField;

		private extensionsType extensionsField;

		private string versionField;

		private string creatorField;

		public gpxType()
		{
			versionField = "1.1";
		}

		/// <remarks/>
		public metadataType metadata
		{
			get { return metadataField; }
			set { metadataField = value; }
		}

		/// <remarks/>
		[XmlElement("wpt")]
		public wptType[] wpt
		{
			get { return wptField; }
			set { wptField = value; }
		}

		/// <remarks/>
		[XmlElement("rte")]
		public rteType[] rte
		{
			get { return rteField; }
			set { rteField = value; }
		}

		/// <remarks/>
		[XmlElement("trk")]
		public trkType[] trk
		{
			get { return trkField; }
			set { trkField = value; }
		}

		/// <remarks/>
		public extensionsType extensions
		{
			get { return extensionsField; }
			set { extensionsField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public string version
		{
			get { return versionField; }
			set { versionField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public string creator
		{
			get { return creatorField; }
			set { creatorField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class metadataType
	{

		private string nameField;

		private string descField;

		private personType authorField;

		private copyrightType copyrightField;

		private linkType[] linkField;

		private DateTime timeField;

		private bool timeFieldSpecified;

		private string keywordsField;

		private boundsType boundsField;

		private extensionsType extensionsField;

		/// <remarks/>
		public string name
		{
			get { return nameField; }
			set { nameField = value; }
		}

		/// <remarks/>
		public string desc
		{
			get { return descField; }
			set { descField = value; }
		}

		/// <remarks/>
		public personType author
		{
			get { return authorField; }
			set { authorField = value; }
		}

		/// <remarks/>
		public copyrightType copyright
		{
			get { return copyrightField; }
			set { copyrightField = value; }
		}

		/// <remarks/>
		[XmlElement("link")]
		public linkType[] link
		{
			get { return linkField; }
			set { linkField = value; }
		}

		/// <remarks/>
		public DateTime time
		{
			get { return timeField; }
			set { timeField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool timeSpecified
		{
			get { return timeFieldSpecified; }
			set { timeFieldSpecified = value; }
		}

		/// <remarks/>
		public string keywords
		{
			get { return keywordsField; }
			set { keywordsField = value; }
		}

		/// <remarks/>
		public boundsType bounds
		{
			get { return boundsField; }
			set { boundsField = value; }
		}

		/// <remarks/>
		public extensionsType extensions
		{
			get { return extensionsField; }
			set { extensionsField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class personType
	{

		private string nameField;

		private emailType emailField;

		private linkType linkField;

		/// <remarks/>
		public string name
		{
			get { return nameField; }
			set { nameField = value; }
		}

		/// <remarks/>
		public emailType email
		{
			get { return emailField; }
			set { emailField = value; }
		}

		/// <remarks/>
		public linkType link
		{
			get { return linkField; }
			set { linkField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class emailType
	{

		private string idField;

		private string domainField;

		/// <remarks/>
		[XmlAttribute]
		public string id
		{
			get { return idField; }
			set { idField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public string domain
		{
			get { return domainField; }
			set { domainField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class trksegType
	{

		private wptType[] trkptField;

		private extensionsType extensionsField;

		/// <remarks/>
		[XmlElement("trkpt")]
		public wptType[] trkpt
		{
			get { return trkptField; }
			set { trkptField = value; }
		}

		/// <remarks/>
		public extensionsType extensions
		{
			get { return extensionsField; }
			set { extensionsField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class wptType
	{

		private decimal eleField;

		private bool eleFieldSpecified;

		private DateTime timeField;

		private bool timeFieldSpecified;

		private decimal magvarField;

		private bool magvarFieldSpecified;

		private decimal geoidheightField;

		private bool geoidheightFieldSpecified;

		private string nameField;

		private string cmtField;

		private string descField;

		private string srcField;

		private linkType[] linkField;

		private string symField;

		private string typeField;

		private fixType fixField;

		private bool fixFieldSpecified;

		private string satField;

		private decimal hdopField;

		private bool hdopFieldSpecified;

		private decimal vdopField;

		private bool vdopFieldSpecified;

		private decimal pdopField;

		private bool pdopFieldSpecified;

		private decimal ageofdgpsdataField;

		private bool ageofdgpsdataFieldSpecified;

		private string dgpsidField;

		private extensionsType extensionsField;

		private decimal latField;

		private decimal lonField;

		/// <remarks/>
		public decimal ele
		{
			get { return eleField; }
			set { eleField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool eleSpecified
		{
			get { return eleFieldSpecified; }
			set { eleFieldSpecified = value; }
		}

		/// <remarks/>
		public DateTime time
		{
			get { return timeField; }
			set { timeField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool timeSpecified
		{
			get { return timeFieldSpecified; }
			set { timeFieldSpecified = value; }
		}

		/// <remarks/>
		public decimal magvar
		{
			get { return magvarField; }
			set { magvarField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool magvarSpecified
		{
			get { return magvarFieldSpecified; }
			set { magvarFieldSpecified = value; }
		}

		/// <remarks/>
		public decimal geoidheight
		{
			get { return geoidheightField; }
			set { geoidheightField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool geoidheightSpecified
		{
			get { return geoidheightFieldSpecified; }
			set { geoidheightFieldSpecified = value; }
		}

		/// <remarks/>
		public string name
		{
			get { return nameField; }
			set { nameField = value; }
		}

		/// <remarks/>
		public string cmt
		{
			get { return cmtField; }
			set { cmtField = value; }
		}

		/// <remarks/>
		public string desc
		{
			get { return descField; }
			set { descField = value; }
		}

		/// <remarks/>
		public string src
		{
			get { return srcField; }
			set { srcField = value; }
		}

		/// <remarks/>
		[XmlElement("link")]
		public linkType[] link
		{
			get { return linkField; }
			set { linkField = value; }
		}

		/// <remarks/>
		public string sym
		{
			get { return symField; }
			set { symField = value; }
		}

		/// <remarks/>
		public string type
		{
			get { return typeField; }
			set { typeField = value; }
		}

		/// <remarks/>
		public fixType fix
		{
			get { return fixField; }
			set { fixField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool fixSpecified
		{
			get { return fixFieldSpecified; }
			set { fixFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlElement(DataType = "nonNegativeInteger")]
		public string sat
		{
			get { return satField; }
			set { satField = value; }
		}

		/// <remarks/>
		public decimal hdop
		{
			get { return hdopField; }
			set { hdopField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool hdopSpecified
		{
			get { return hdopFieldSpecified; }
			set { hdopFieldSpecified = value; }
		}

		/// <remarks/>
		public decimal vdop
		{
			get { return vdopField; }
			set { vdopField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool vdopSpecified
		{
			get { return vdopFieldSpecified; }
			set { vdopFieldSpecified = value; }
		}

		/// <remarks/>
		public decimal pdop
		{
			get { return pdopField; }
			set { pdopField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool pdopSpecified
		{
			get { return pdopFieldSpecified; }
			set { pdopFieldSpecified = value; }
		}

		/// <remarks/>
		public decimal ageofdgpsdata
		{
			get { return ageofdgpsdataField; }
			set { ageofdgpsdataField = value; }
		}

		/// <remarks/>
		[XmlIgnore]
		public bool ageofdgpsdataSpecified
		{
			get { return ageofdgpsdataFieldSpecified; }
			set { ageofdgpsdataFieldSpecified = value; }
		}

		/// <remarks/>
		[XmlElement(DataType = "integer")]
		public string dgpsid
		{
			get { return dgpsidField; }
			set { dgpsidField = value; }
		}

		/// <remarks/>
		public extensionsType extensions
		{
			get { return extensionsField; }
			set { extensionsField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public decimal lat
		{
			get { return latField; }
			set { latField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public decimal lon
		{
			get { return lonField; }
			set { lonField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class linkType
	{

		private string textField;

		private string typeField;

		private string hrefField;

		/// <remarks/>
		public string text
		{
			get { return textField; }
			set { textField = value; }
		}

		/// <remarks/>
		public string type
		{
			get { return typeField; }
			set { typeField = value; }
		}

		/// <remarks/>
		[XmlAttribute(DataType = "anyURI")]
		public string href
		{
			get { return hrefField; }
			set { hrefField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public enum fixType
	{

		/// <remarks/>
		none,

		/// <remarks/>
		[XmlEnum("2d")] Item2d,

		/// <remarks/>
		[XmlEnum("3d")] Item3d,

		/// <remarks/>
		dgps,

		/// <remarks/>
		pps
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class extensionsType
	{

		private XmlElement[] anyField;

		/// <remarks/>
		[XmlAnyElement]
		public XmlElement[] Any
		{
			get { return anyField; }
			set { anyField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class trkType
	{

		private string nameField;

		private string cmtField;

		private string descField;

		private string srcField;

		private linkType[] linkField;

		private string numberField;

		private string typeField;

		private extensionsType extensionsField;

		private trksegType[] trksegField;

		/// <remarks/>
		public string name
		{
			get { return nameField; }
			set { nameField = value; }
		}

		/// <remarks/>
		public string cmt
		{
			get { return cmtField; }
			set { cmtField = value; }
		}

		/// <remarks/>
		public string desc
		{
			get { return descField; }
			set { descField = value; }
		}

		/// <remarks/>
		public string src
		{
			get { return srcField; }
			set { srcField = value; }
		}

		/// <remarks/>
		[XmlElement("link")]
		public linkType[] link
		{
			get { return linkField; }
			set { linkField = value; }
		}

		/// <remarks/>
		[XmlElement(DataType = "nonNegativeInteger")]
		public string number
		{
			get { return numberField; }
			set { numberField = value; }
		}

		/// <remarks/>
		public string type
		{
			get { return typeField; }
			set { typeField = value; }
		}

		/// <remarks/>
		public extensionsType extensions
		{
			get { return extensionsField; }
			set { extensionsField = value; }
		}

		/// <remarks/>
		[XmlElement("trkseg")]
		public trksegType[] trkseg
		{
			get { return trksegField; }
			set { trksegField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class rteType
	{

		private string nameField;

		private string cmtField;

		private string descField;

		private string srcField;

		private linkType[] linkField;

		private string numberField;

		private string typeField;

		private extensionsType extensionsField;

		private wptType[] rteptField;

		/// <remarks/>
		public string name
		{
			get { return nameField; }
			set { nameField = value; }
		}

		/// <remarks/>
		public string cmt
		{
			get { return cmtField; }
			set { cmtField = value; }
		}

		/// <remarks/>
		public string desc
		{
			get { return descField; }
			set { descField = value; }
		}

		/// <remarks/>
		public string src
		{
			get { return srcField; }
			set { srcField = value; }
		}

		/// <remarks/>
		[XmlElement("link")]
		public linkType[] link
		{
			get { return linkField; }
			set { linkField = value; }
		}

		/// <remarks/>
		[XmlElement(DataType = "nonNegativeInteger")]
		public string number
		{
			get { return numberField; }
			set { numberField = value; }
		}

		/// <remarks/>
		public string type
		{
			get { return typeField; }
			set { typeField = value; }
		}

		/// <remarks/>
		public extensionsType extensions
		{
			get { return extensionsField; }
			set { extensionsField = value; }
		}

		/// <remarks/>
		[XmlElement("rtept")]
		public wptType[] rtept
		{
			get { return rteptField; }
			set { rteptField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class boundsType
	{

		private decimal minlatField;

		private decimal minlonField;

		private decimal maxlatField;

		private decimal maxlonField;

		/// <remarks/>
		[XmlAttribute]
		public decimal minlat
		{
			get { return minlatField; }
			set { minlatField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public decimal minlon
		{
			get { return minlonField; }
			set { minlonField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public decimal maxlat
		{
			get { return maxlatField; }
			set { maxlatField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public decimal maxlon
		{
			get { return maxlonField; }
			set { maxlonField = value; }
		}
	}

	/// <remarks/>
	[GeneratedCode("xsd", "4.0.30319.1")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "http://www.topografix.com/GPX/1/1")]
	public class copyrightType
	{

		private string yearField;

		private string licenseField;

		private string authorField;

		/// <remarks/>
		[XmlElement(DataType = "gYear")]
		public string year
		{
			get { return yearField; }
			set { yearField = value; }
		}

		/// <remarks/>
		[XmlElement(DataType = "anyURI")]
		public string license
		{
			get { return licenseField; }
			set { licenseField = value; }
		}

		/// <remarks/>
		[XmlAttribute]
		public string author
		{
			get { return authorField; }
			set { authorField = value; }
		}
	}
}